<?php 
   session_start();
   
   $admin_id = $_SESSION['admin-id'];
   
   include "../includes/db_con.php";
   include "../includes/select_all.php";
   include "../includes/date_today.php";

   
   $date_today = new DateTime($date_today);
   $date_today = $date_today->format("F d, Y h:i A");

   // image
   $header_svg = file_get_contents("../../assets/header-report.png");
   $header_base64 = base64_encode($header_svg);

   $type = $_GET['type'];
   $dateRange = $_GET['dateRange'];

   $abuseAnimal = "SELECT * FROM `abuse_report` a 
   JOIN `user_details` c 
   ON a.user_id = c.user_id 
   WHERE `type_of_report` = 'Abused Animal'";
   
   $wildAnimal = "SELECT * FROM `abuse_report` a 
   JOIN `user_details` c 
   ON a.user_id = c.user_id 
   WHERE `type_of_report` = 'Wild Animal'";


   switch ($dateRange){

      case "week":
         $prevWeek = strtotime('-1 week +1 day');

         $fromDate = strtotime("last sunday midnight",$prevWeek);
         $toDate = strtotime("saturday",$prevWeek);

         $fromDate = date("Y-m-d", $fromDate);
         $toDate = date("Y-m-d", $toDate);

         $abuseAnimal .= " AND (DATE(a.`datetime`) BETWEEN '$fromDate' AND '$curr_date')";
         $wildAnimal .= " AND (DATE(a.`datetime`) BETWEEN '$fromDate' AND '$curr_date')";

      break;

      case "month":
         $fromDate = date('Y-m-d', strtotime('first day of last month'));
         $toDate = date('Y-m-d', strtotime('last day of last month'));

         $abuseAnimal .= " AND (a.DATE(`datetime`) BETWEEN '$fromDate' AND '$curr_date')";
         $wildAnimal .= " AND (a.DATE(`datetime`) BETWEEN '$fromDate' AND '$curr_date')";

      break;
      
      case "year":
         $lastyear = date("Y") - 1;    

         $abuseAnimal .= " AND a.`datetime` LIKE '%$lastyear%'";
         $wildAnimal .= " AND a.`datetime` LIKE '%$lastyear%'";

      break;

   }
   
   $wildAnimal .= "ORDER BY a.id DESC";
   $abuseAnimal .= "ORDER BY a.id DESC";

   $abuse = mysqli_query($conn, $abuseAnimal);

   $wild = mysqli_query($conn, $wildAnimal);

?>

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title> Reported Animals Summary Report </title>
   <!-- <link rel="stylesheet" href="../css/main.css"> -->

   <!-- Chart Js CDN -->
   <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.0/dist/chart.umd.min.js"></script>
</head>

<style>

   body{
      font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
   }

   header{
      background-color: red;
   }

   header img{
      width: 100%;
   }

   main .header-title{
      text-align: center;
   }

   main .main-content{
      /* background-color: red; */
      margin-bottom: 5px;
   }

   main .main-content .item-list{
      margin-bottom: 20px;
   }

   main .main-content .item-list table{
      width: 100%;
      border-collapse: collapse;
      text-align: center;
      margin-bottom: 20px;
      
   }

   main .main-content .item-list table thead{
      background-color: #ddd;
      font-weight: 400;
   }

   main .main-content .item-list table thead th{
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: .85em;
      padding: 5px;
   }

   main .main-content .item-list table thead td{
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: .80em;
      padding: 5px;
   }

   main .main-content .item-list table tbody td{
      font-size: .85em;
      padding: 5px;
   }


   main .main-content .summary-container table{
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 20px;
   }

   main .main-content .summary-container table tr td{
     padding: 5px;
   }

   footer{
      position: absolute;
      bottom: 1%;
      width: 100%;
   }

   footer p{
      font-size: .8em;
   }

</style>

<body>

   <header>
      <img src='data:image;base64, <?=$header_base64?>'>
   </header>

   <main>
        <p> Control number: <b> <?=generateID(6);?> </b> </p>
       
        <div class="header-title">
            
            <div>
                <p style="display:flex; float: left; text-transform: capitalize;"> Generated by: <b> <?=$admin_logged['firstname']?> <?=$admin_logged['lastname']?> </b></p>

                <p  style="display:flex; float: right;"> Date & time: <b> <?=$date_today;?> </b> </p>
            </div>
            
            <h3 style="text-transform: capitalize;"> <u> Reported animal Last <?=$dateRange?> summary report </u> </h3>

        </div>

      <div class="main-content">

         <div class="item-list">

            <table>
               <tr>
                  <td style="text-align: left;"> Total reported animals: <?=mysqli_num_rows($wild) + mysqli_num_rows($abuse)?></td>
               </tr>
            </table>

            <table border="1">
               <thead>

                  <tr>
                     <th colspan="7" style="text-align: left;"> List of wild animals: <?=mysqli_num_rows($wild)?></th>
                  </tr>

                  <tr>
                     <td> Id </td>
                     <td> Report ID </td>
                     <td> User </td>
                     <!-- <td> Description </td> -->
                     <td> Address </th>
                     <td> Date reported </td>
                     <td> Action Taken </td>
                     <td> Processed by </td>
                  </tr>

               </thead>

               <tbody>
                  <?php 
                     if(mysqli_num_rows($wild) > 0) {
                        $id = 1;
                        while($row = mysqli_fetch_assoc($wild)){ 

                           $processedby = $row['processed_by'];

                           // $dateReported = date

                           $dateReported = $row['datetime'];
                           $dateReported = new DateTime($dateReported);
                           $dateReported = $dateReported->format("F d, Y");

                           $selAdmin = mysqli_query($conn, "SELECT * FROM `admin_info` WHERE `admin_id` = '$processedby';");

                           $admin = mysqli_fetch_assoc($selAdmin);

                           ?>
                              <tr>
                                 <td> <?=$id?> </td>
                                 <td> <?=$row['report_id']?> </td>
                                 <td> <?=$row['firstname']?> <?=$row['lastname']?></td>
                                 <!-- <td> <?=$row['description']?> </td> -->
                                 <td> <?=$row['address']?> </th>
                                 <td> <?=$dateReported?> </td>
                                 <td> <?=$row['action_taken']?> </td>
                                 <td> <?=$admin['firstname']?> <?=$admin['lastname']?></td>
                              </tr>
                           <?php
                           $id++;
                        }
                     } else {
                        echo "<tr> <td colspan='7'> No data </td> </tr>";
                     }
                  ?>
                  
               </tbody>

               
            </table>

            <table border="1">
               <thead>

                  <tr>
                     <th colspan="7" style="text-align: left;"> List of abuse animals: <?=mysqli_num_rows($abuse)?></th>
                  </tr>

                  <tr>
                     <td> Id </td>
                     <td> Report ID </td>
                     <td> User </td>
                     <!-- <td> Description </td> -->
                     <td> Address </th>
                     <td> Date reported </td>
                     <td> Action Taken </td>
                     <td> Processed by </td>
                  </tr>

               </thead>

               <tbody>
                  <?php 
                     if(mysqli_num_rows($abuse) > 0) {
                        $id = 1;
                        while($row = mysqli_fetch_assoc($abuse)){ 

                           $processedby = $row['processed_by'];

                           // $dateReported = date

                           $dateReported = $row['datetime'];
                           $dateReported = new DateTime($dateReported);
                           $dateReported = $dateReported->format("F d, Y");

                           $selAdmin = mysqli_query($conn, "SELECT * FROM `admin_info` WHERE `admin_id` = '$processedby';");

                           $admin = mysqli_fetch_assoc($selAdmin);

                           ?>
                           <tr>
                              <td> <?=$id?> </td>
                              <td> <?=$row['report_id']?> </td>
                              <td> <?=$row['firstname']?> <?=$row['lastname']?></td>
                              <!-- <td> <?=$row['description']?> </td> -->
                              <td> <?=$row['address']?> </th>
                              <td> <?=$dateReported?> </td>
                              <td> <?=$row['action_taken']?> </td>
                              <td> <?=$admin['firstname']?> <?=$admin['lastname']?></td>
                           </tr>
                           <?php
                           $id++;
                        }
                     } else {
                        echo "<tr> <td colspan='7'> No data </td> </tr>";
                     }
                  ?>
                  
               </tbody>
            </table>

         </div>

         
      </div>
   </main>

   <!--<footer>-->
   <!--   <p style="display:flex; float: left; text-transform: capitalize;"> Generated by: <b> <?=$admin_logged['firstname']?> <?=$admin_logged['lastname']?> </b></p>-->

   <!--   <p  style="display:flex; float: right;"> Date & time: <b> <?=$date_today;?> </b> </p>-->
   <!--</footer>-->
   
</body>
<?php 

function generateID($len){

   $characters = '0123456789';

   $code = '';

   for ($i = 0; $i < $len; $i++) {

       $code .= $characters[rand(0, strlen($characters) - 1)];
   }

   return $code;

}

?>

</html>