<?php 
   session_start();
   
   $admin_id = $_SESSION['admin-id'];
   
   include "../includes/db_con.php";
   include "../includes/select_all.php";
   include "../includes/date_today.php";

   
   $date_today = new DateTime($date_today);
   $date_today = $date_today->format("F d, Y h:i A");

   // image
   $header_svg = file_get_contents("../../assets/header-report.png");
   $header_base64 = base64_encode($header_svg);

   $type = $_GET['type'];
   $dateRange = $_GET['dateRange'];

   $sql = "SELECT * FROM `services_transaction`
   WHERE `status` = 'attended'";


   // TOTAL PROFIT

   switch ($dateRange){
      case "week": 

         $prevWeek = strtotime('-1 week +1 day');

         $fromDate = strtotime("last sunday midnight",$prevWeek);
         $toDate = strtotime("saturday",$prevWeek);

         $fromDate = date("Y-m-d", $fromDate);
         $toDate = date("Y-m-d", $toDate);

         $sql .= " AND DATE(`schedule`) BETWEEN '$fromDate' AND '$curr_date';";

         break;

      case "month":
         $fromDate = date('Y-m-d', strtotime('first day of last month'));
         $toDate = date('Y-m-d', strtotime('last day of last month'));

         $sql .= " AND DATE(`schedule`) BETWEEN '$fromDate' AND '$curr_date';";
        

         break;
      

      case "year":

         $lastyear = date("Y") - 1;
         
         $sql .= " AND `schedule` LIKE '%$lastyear%'";

         break;

   }

   $result = mysqli_query($conn, $sql);
   

?>

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title> Services Summary Report </title>
   <!-- <link rel="stylesheet" href="../css/main.css"> -->

   <!-- Chart Js CDN -->
   <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.0/dist/chart.umd.min.js"></script>
</head>

<style>

   body{
      font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
   }

   header{
      background-color: red;
   }

   header img{
      width: 100%;
   }

   main .header-title{
      text-align: center;
   }

   main .main-content{
      /* background-color: red; */
      margin-bottom: 5px;
   }

   main .main-content .item-list{
      margin-bottom: 20px;
   }

   main .main-content .item-list table{
      width: 100%;
      border-collapse: collapse;
      text-align: center;
      
   }

   main .main-content .item-list table thead{
      background-color: #ddd;
      font-weight: 400;
   }

   main .main-content .item-list table thead th{
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: .9em;
      padding: 5px;
   }

   main .main-content .item-list table tbody td{
      font-size: .85em;
      padding: 5px;
   }

   main .main-content .summary-container{
      margin-bottom: 20px;
   }

   main .main-content .summary-container table{
      width: 100%;
      border-collapse: collapse;
      text-align: center;
      margin-bottom: 20px;
   }

   main .main-content .summary-container table thead th{
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: .9em;
      padding: 5px 10px;
      text-align: left;
      background-color: #ddd;
   }

   main .main-content .summary-container table thead td{
      font-size: .9em;
      padding: 5px 10px;
      background-color: #ddd;
   }

   main .main-content .summary-container table tbody td{
     padding: 5px;
     font-size: .9em;
   }






   footer{
      position: absolute;
      bottom: 1%;
      width: 100%;
   }

   footer p{
      font-size: .8em;
   }

</style>

<body>

   <header>

      <img src='data:image;base64, <?=$header_base64?>'>

   </header>

   <main>
       <p> Control number: <b> <?=generateID(6);?> </b> </p>
            <div style="margin-bottom: 40px;">
                <p style="display:flex; float: left; text-transform: capitalize;"> Generated by: <b> <?=$admin_logged['firstname']?> <?=$admin_logged['lastname']?> </b></p>

                <p  style="display:flex; float: right;"> Date & time: <b> <?=$date_today;?> </b> </p>
            </div>
        <div class="header-title">
            
         <h2 style="text-transform: capitalize;"> <u> <?=$type?> Last <?=$dateRange?> summary report </u> </h2>
         <!-- <p> <?=$sql?></p> -->
         
      </div>

      <div class="main-content">

         <!-- <div class="item-list">

            <table border="1">
               <thead>
                  <tr>
                     <th colspan="5"> Overall: <b> <?=mysqli_num_rows($result)?></b></th>
                  </tr>
                  <tr>
                     <th> Application No. </th>
                     <th> User ID </th>
                     <th> Service </th>
                     <th> Application Date </th>
                     <th> Date process </th>
                  </tr>
               </thead>

               <tbody>
                  <?php 
                     if(mysqli_num_rows($result) > 0){

                        while($row = mysqli_fetch_assoc($result)){

                           $date_apply = $row['date_apply'];
                           $date_apply = new DateTime($date_apply);
                           $date_apply = $date_apply->format("F d, Y");

                           $sched = $row['schedule'];
                           $sched = new DateTime($sched);
                           $sched = $sched->format("F d, Y");

                           ?>
                              <tr>
                                 <td> <?=$row['reference_no']?> </td>
                                 <td> <?=$row['user_id']?> </td>
                                 <td style="text-transform:capitalize"> <?=$row['type_of_service']?> </td>
                                 <td> <?=$date_apply?> </td>
                                 <td><?=$sched?></td>
                              </tr>
                           <?php 

                        }
                        
                     } else {
                        ?> <tr> <td colspan="6"> No data </td> </tr> <?php 
                     }
                  ?>
               
               </tbody>
            </table>

         </div> -->

         <div class="summary-container">

            <div class="total">
               <p> Total Avail Services: <b> <?=mysqli_num_rows($result)?> </b></p>
            </div>

            <?php 
               $servicesQry = mysqli_query($conn, "SELECT * FROM `services`");

                  if(mysqli_num_rows($servicesQry)> 0) {
                     while($row = mysqli_fetch_assoc($servicesQry)){

                        $serviceType = $row['type_of_service'];

                        $serviceTotal = "SELECT * FROM `services_transaction` WHERE `status` = 'attended' AND type_of_service = '$serviceType' AND DATE(`schedule`) BETWEEN '$fromDate' AND '$toDate';";
                        
                        $cntSe = mysqli_query($conn, $serviceTotal);

                      
                      
                        ?>

                        <table border="1">
                           <thead>
                              <tr>
                                 <th colspan="4">  <?=$serviceType?>: <b><?=mysqli_num_rows($cntSe)?> </b> </th>
                              </tr>

                              <tr>
                                 <td> Application No. </td>
                                 <td> User ID </td>
                                 <td> Application Date </td>
                                 <td> Date process </td>
                              </tr>
                           </thead>

                           <tbody>
                              <?php
                                 if(mysqli_num_rows($cntSe)>0){
                                    while($row = mysqli_fetch_assoc($cntSe)){

                                                   
                                    $date_apply = $row['date_apply'];
                                    $date_apply = new DateTime($date_apply);
                                    $date_apply = $date_apply->format("F d, Y");

                                    $sched = $row['schedule'];
                                    $sched = new DateTime($sched);
                                    $sched = $sched->format("F d, Y");
                                    
                                       ?>

                                       <tr>
                                          <td> <?=$row['reference_no']?> </td>
                                          <td> <?=$row['user_id']?> </td>
                                          <td> <?=$date_apply?> </td>
                                          <td><?=$sched?></td>
                                       </tr>

                                       <?php 
                                    }

                                 } else {
                                    ?>
                                    <tr>
                                       <td colspan="4" style="text-align: center;"> No data </td>
                                    </tr>
                                    <?php 
                                 }
                              ?>
                              

                           </tbody>
                           
                        </table>
                        
                      <?php 
                   }
                  
                  }
               
               ?>
         </div>

      </div>
   </main>

   <!--<footer>-->
   <!--   <p style="display:flex; float: left; text-transform: capitalize;"> Generated by: <b> <?=$admin_logged['firstname']?> <?=$admin_logged['lastname']?> </b></p>-->

   <!--   <p  style="display:flex; float: right;"> Date & time: <b> <?=$date_today;?> </b> </p>-->
   <!--</footer>-->
   
</body>

<?php 

function generateID($len){

   $characters = '0123456789';

   $code = '';

   for ($i = 0; $i < $len; $i++) {

       $code .= $characters[rand(0, strlen($characters) - 1)];
   }

   return $code;

}

?>

</html>